# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

submodules:
  include: all

# Build your docs in additional formats such as PDF and ePub
formats: all

# Set the version of Python and OS
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.6"
  apt_packages:
    - clang
  commands:
    - pwd && ls
    - ls src/main/python/pyPOCQuantUI/
    # - mkdir -p docs/_static
    - ls docs/
    # - mkdir -p $READTHEDOCS_OUTPUT/html/ui_images
    # - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/ui_images $READTHEDOCS_OUTPUT/html/ui_images


# Install requirements required to build your docs
python:
  install:
    - requirements: requirements/linux.txt
