# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

submodules:
  include: all

# Build your docs in additional formats such as PDF and ePub
formats: all

# Install requirements required to build your docs
python:
  install:
    - requirements: requirements/linux.txt

# Set the version of Python and OS
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.6"
  apt_packages:
    - clang
  jobs:
    post_install:
      - pwd && ls
      - ls src/main/python/pyPOCQuantUI/
      - mkdir -p docs/_static
      - mkdir -p docs/_build/html
      - ls docs/
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/ui_images docs/_build/html/ui_images
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/ui_images docs/_build/ui_images
      - ls docs/_build/html/ui_images


