# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Build documentation with MkDocs
#mkdocs:
#  configuration: mkdocs.yml

submodules:
  include: all

# Build your docs in additional formats such as PDF and ePub
formats: all

# Install requirements required to build your docs
python:
  install:
    - requirements: requirements/linux.txt

# Set the version of Python and OS
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.6"
  apt_packages:
    - clang
  jobs:
    post_build:
      - pwd && ls
      - ls src/main/python/pyPOCQuantUI/
      - mkdir -p ../latest/_readthedocs/html/ui_images
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/ui_images/* ../latest/_readthedocs/html/ui_images
      - mkdir -p ../latest/_readthedocs/html/demo_image
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/demo_image/* ../latest/_readthedocs/html/demo_image
      - mkdir -p ../latest/_readthedocs/html/problem_solutions
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/problem_solutions/* ../latest/_readthedocs/html/problem_solutions
      - mkdir -p ../latest/_readthedocs/html/setup
      - cp -r src/main/python/pyPOCQuantUI/pypocquant/manual/setup/* ../latest/_readthedocs/html/setup
      - mkdir -p ../latest/_readthedocs/html/src/main/resources/base/img
      - cp -r src/main//resources/base/img/* ../latest/_readthedocs/html/src/main/resources/base/img
      - ls -R ../
      # - python -m sphinx -b html docs/ docs/_build/html


